#!/usr/bin/env groovy


// Declarative //
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building Declarative ...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing Declarative ...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying Declarative ...'
            }
        }
    }
}

// Script //
node {
checkout scm
    stage('Build') {
        echo 'Building Script ...'
    }
    stage('Test') {
        echo 'Testing Script ...'
    }
    stage('Deploy') {
        echo 'Deploying Script ...'
    }
}