#!/usr/bin/env groovy


node {
checkout scm

   stage('Build') {
      echo 'Building Script ...'
     }

     stage('Test') {
        echo 'Testing Script ...'
     }

     stage('Deploy') {
        echo 'Deploying Script ...'
    }

}