#!/usr/bin/env groovy



// Script //
node {
    stage('Build') {
        echo 'Building Script ...'
    }
    stage('Test') {
        echo 'Testing Script ...'
    }
    stage('Deploy') {
        echo 'Deploying Script ...'
    }
}